import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useRef} from "react";
import {
    Box,
    Button,
    Container, Grid, Heading,
    HStack, IconButton, Image,
    Input,
    InputGroup,
    InputLeftAddon,
    InputRightAddon, ListItem, SimpleGrid,
    Stack, Text, UnorderedList, VStack
} from "@chakra-ui/react";

import SwiperCore, {
    Pagination, Navigation
} from 'swiper';
import {Swiper, SwiperSlide} from "swiper/react";
import {MdNavigateBefore, MdNavigateNext} from "react-icons/md";
import {useRouter} from "next/router";
import StandartLayout from "../components/layouts/StandartLayout";


SwiperCore.use([Pagination, Navigation]);


export default function Home() {
    const router = useRouter();
    const prevRefBoard = useRef(null);
    const nextRefBoard = useRef(null);
    const prevRefCategories = useRef(null);
    const nextRefCategories = useRef(null);
    return (
        <>
            <Head>
                <title>Degree Project</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>



            <StandartLayout>
                <Container maxW={"container.xl"}>
                    <HStack justify={"space-between"} align={"center"} mt={6} mb={2}>
                        <Box borderLeft={"4px"} borderColor={"specialColors.portland_orange.500"} paddingLeft={2}>
                            <Text fontSize='2xl' fontWeight={"semibold"}>Bunları Sizin İçin Seçtik</Text>
                        </Box>

                        <HStack spacing={4}>
                            <IconButton aria-label='Previous Slide' colorScheme={"specialColors.portland_orange"}
                                        fontSize={"2rem"} ref={prevRefBoard} icon={<MdNavigateBefore/>}/>

                            <IconButton aria-label='Previous Slide' colorScheme={"specialColors.portland_orange"}
                                        fontSize={"2rem"} ref={nextRefBoard} icon={<MdNavigateNext/>}/>
                        </HStack>
                    </HStack>

                    <Box width={"100%"}>
                        <Swiper slidesPerView={2} spaceBetween={36}
                                onInit={(swiper) => {
                                    swiper.params.navigation.prevEl = prevRefBoard.current;
                                    swiper.params.navigation.nextEl = nextRefBoard.current;
                                    swiper.navigation.init();
                                    swiper.navigation.update();
                                }}
                        >
                            <SwiperSlide>
                                <Box bg={"white"} boxShadow={"md"} minHeight={400} w={"100%"}
                                     rounded={"md"} overflow={"hidden"}>

                                    <Image src={"/assets/images/1.jpg"} width={"full"} height={220}
                                           objectFit={"cover"}></Image>

                                    <VStack align={"start"} my={3} px={4} spacing={4}>
                                        <Text fontSize='2xl' fontWeight={"semibold"} lineHeight={"1.6rem"}>Header OneHeader
                                            OneHeader OneHeader OneHeader OneHeader One</Text>

                                        <Text textAlign={"justify"}>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                                            Praesent et lectus tortor. Nulla quam ipsum, aliquet commodo tellus ac,
                                            ultricies condimentum leo.</Text>

                                        <Button width={"full"}>Teste Git</Button>
                                    </VStack>
                                </Box>
                            </SwiperSlide>

                            <SwiperSlide>
                                <Box bg={"white"} boxShadow={"md"} minHeight={400} w={'100%'}
                                     rounded={"md"} overflow={"hidden"}>
                                    <Image src={"/assets/images/2.jpg"} width={"full"} height={220}
                                           objectFit={"cover"}></Image>

                                    <VStack align={"start"} my={3} px={4} spacing={4}>
                                        <Text fontSize='2xl' as='b' lineHeight={"1.6rem"}>Header OneHeader OneHeader
                                            OneHeader OneHeader OneHeader One</Text>

                                        <Text textAlign={"justify"}>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                                            Praesent et lectus tortor. Nulla quam ipsum, aliquet commodo tellus ac,
                                            ultricies condimentum leo.</Text>

                                        <Button width={"full"}>Teste Git</Button>
                                    </VStack>
                                </Box>
                            </SwiperSlide>

                            <SwiperSlide>
                                <Box bg={"white"} boxShadow={"md"} minHeight={400} w={'100%'}
                                     rounded={"md"} overflow={"hidden"}>
                                    <Image src={"/assets/images/3.jpg"} width={"full"} height={220}
                                           objectFit={"cover"}></Image>

                                    <VStack align={"start"} my={3} px={4} spacing={4}>
                                        <Text fontSize='2xl' as='b' lineHeight={"1.6rem"}>Header OneHeader OneHeader
                                            OneHeader OneHeader OneHeader One</Text>

                                        <Text textAlign={"justify"}>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                                            Praesent et lectus tortor. Nulla quam ipsum, aliquet commodo tellus ac,
                                            ultricies condimentum leo.</Text>

                                        <Button width={"full"}>Teste Git</Button>
                                    </VStack>
                                </Box>
                            </SwiperSlide>

                            <SwiperSlide>
                                <Box bg={"white"} boxShadow={"md"} minHeight={240} w={'100%'} color='white'
                                     rounded={"md"}>
                                    <Image src={"/assets/images/3.jpg"} width={"full"} height={120}
                                           objectFit={"cover"}></Image>
                                    This is the Box
                                </Box>
                            </SwiperSlide>

                            <SwiperSlide>
                                <Box bg={"white"} boxShadow={"md"} minHeight={240} w={'100%'} color='white'
                                     rounded={"md"}>
                                    <Image src={"/assets/images/3.jpg"} width={"full"} height={120}
                                           objectFit={"cover"}></Image>
                                    This is the Box
                                </Box>
                            </SwiperSlide>
                        </Swiper>
                    </Box>
                </Container>

                <Container maxW={"container.xl"}>
                    <HStack justify={"space-between"} align={"center"} mt={6} mb={2}>
                        <Box borderLeft={"4px"} borderColor={"specialColors.portland_orange.500"} paddingLeft={2}>
                            <Text fontSize='2xl' fontWeight={"semibold"}>Kategoriler</Text>
                        </Box>
                        <HStack spacing={4}>
                            <IconButton aria-label='Previous Slide' colorScheme={"specialColors.portland_orange"}
                                        fontSize={"2rem"} ref={prevRefCategories} icon={<MdNavigateBefore/>}/>
                            <IconButton aria-label='Previous Slide' colorScheme={"specialColors.portland_orange"}
                                        fontSize={"2rem"} ref={nextRefCategories} icon={<MdNavigateNext/>}/>
                        </HStack>
                    </HStack>

                    <Swiper slidesPerView={5} spaceBetween={36} slidesPerColumn={2} slidesPerColumnFill={'row'}
                            onInit={(swiper) => {
                                swiper.params.navigation.prevEl = prevRefCategories.current;
                                swiper.params.navigation.nextEl = nextRefCategories.current;
                                swiper.navigation.init();
                                swiper.navigation.update();
                            }}
                    >
                        <SwiperSlide>
                            <Box
                                background={"linear-gradient(to top, #3204fdba, #9907facc), url(/assets/images/1.jpg) no-repeat"}
                                backgroundSize={"cover"} boxShadow={"md"} h={100} w={"100%"}
                                rounded={"md"} overflow={"hidden"} display={"flex"} alignItems={"center"}
                                justifyContent={"center"}>
                                <Text fontSize='2xl' fontWeight={"semibold"} p={3} color={"white"}> Kategori</Text>
                            </Box>
                        </SwiperSlide>

                        <SwiperSlide>
                            <Box
                                background={"linear-gradient(to top, #3204fdba, #9907facc), url(/assets/images/2.jpg) no-repeat"}
                                backgroundSize={"cover"} boxShadow={"md"} h={100} w={"100%"}
                                rounded={"md"} overflow={"hidden"} display={"flex"} alignItems={"center"}
                                justifyContent={"center"}>
                                <Text fontSize='2xl' fontWeight={"semibold"} p={3} color={"white"}> Kategori</Text>
                            </Box>
                        </SwiperSlide>

                        <SwiperSlide>
                            <Box
                                background={"linear-gradient(to top, #3204fdba, #9907facc), url(/assets/images/3.jpg) no-repeat"}
                                backgroundSize={"cover"} boxShadow={"md"} h={100} w={"100%"}
                                rounded={"md"} overflow={"hidden"} display={"flex"} alignItems={"center"}
                                justifyContent={"center"}>
                                <Text fontSize='2xl' fontWeight={"semibold"} p={3} color={"white"}> Kategori</Text>
                            </Box>
                        </SwiperSlide>

                        <SwiperSlide>
                            <Box
                                background={"linear-gradient(to top, #3204fdba, #9907facc), url(/assets/images/1.jpg) no-repeat"}
                                backgroundSize={"cover"} boxShadow={"md"} h={100} w={"100%"}
                                rounded={"md"} overflow={"hidden"} display={"flex"} alignItems={"center"}
                                justifyContent={"center"}>
                                <Text fontSize='2xl' fontWeight={"semibold"} p={3} color={"white"}> Kategori</Text>
                            </Box>
                        </SwiperSlide>

                        <SwiperSlide>
                            <Box
                                background={"linear-gradient(to top, #3204fdba, #9907facc), url(/assets/images/2.jpg) no-repeat"}
                                backgroundSize={"cover"} boxShadow={"md"} h={100} w={"100%"}
                                rounded={"md"} overflow={"hidden"} display={"flex"} alignItems={"center"}
                                justifyContent={"center"}>
                                <Text fontSize='2xl' fontWeight={"semibold"} p={3} color={"white"}> Kategori</Text>
                            </Box>
                        </SwiperSlide>

                        <SwiperSlide>
                            <Box
                                background={"linear-gradient(to top, #3204fdba, #9907facc), url(/assets/images/3.jpg) no-repeat"}
                                backgroundSize={"cover"} boxShadow={"md"} h={100} w={"100%"}
                                rounded={"md"} overflow={"hidden"} display={"flex"} alignItems={"center"}
                                justifyContent={"center"}>
                                <Text fontSize='2xl' fontWeight={"semibold"} p={3} color={"white"}>Kategori</Text>
                            </Box>
                        </SwiperSlide>

                        <SwiperSlide>
                            <Box
                                background={"linear-gradient(to top, #3204fdba, #9907facc), url(/assets/images/1.jpg) no-repeat"}
                                backgroundSize={"cover"} boxShadow={"md"} h={100} w={"100%"}
                                rounded={"md"} overflow={"hidden"} display={"flex"} alignItems={"center"}
                                justifyContent={"center"}>
                                <Text fontSize='2xl' fontWeight={"semibold"} p={3} color={"white"}> Kategori</Text>
                            </Box>
                        </SwiperSlide>

                        <SwiperSlide>
                            <Box
                                background={"linear-gradient(to top, #3204fdba, #9907facc), url(/assets/images/1.jpg) no-repeat"}
                                backgroundSize={"cover"} boxShadow={"md"} h={100} w={"100%"}
                                rounded={"md"} overflow={"hidden"} display={"flex"} alignItems={"center"}
                                justifyContent={"center"}>
                                <Text fontSize='2xl' fontWeight={"semibold"} p={3} color={"white"}> Kategori</Text>
                            </Box>
                        </SwiperSlide>

                        <SwiperSlide>
                            <Box
                                background={"linear-gradient(to top, #3204fdba, #9907facc), url(/assets/images/1.jpg) no-repeat"}
                                backgroundSize={"cover"} boxShadow={"md"} h={100} w={"100%"}
                                rounded={"md"} overflow={"hidden"} display={"flex"} alignItems={"center"}
                                justifyContent={"center"}>
                                <Text fontSize='2xl' fontWeight={"semibold"} p={3} color={"white"}> Kategori</Text>
                            </Box>
                        </SwiperSlide>

                        <SwiperSlide>
                            <Box
                                background={"linear-gradient(to top, #3204fdba, #9907facc), url(/assets/images/1.jpg) no-repeat"}
                                backgroundSize={"cover"} boxShadow={"md"} h={100} w={"100%"}
                                rounded={"md"} overflow={"hidden"} display={"flex"} alignItems={"center"}
                                justifyContent={"center"}>
                                <Text fontSize='2xl' fontWeight={"semibold"} p={3} color={"white"}> Kategori</Text>
                            </Box>
                        </SwiperSlide>

                        <SwiperSlide>
                            <Box
                                background={"linear-gradient(to top, #3204fdba, #9907facc), url(/assets/images/1.jpg) no-repeat"}
                                backgroundSize={"cover"} boxShadow={"md"} h={100} w={"100%"}
                                rounded={"md"} overflow={"hidden"} display={"flex"} alignItems={"center"}
                                justifyContent={"center"}>
                                <Text fontSize='2xl' fontWeight={"semibold"} p={3} color={"white"}> Kategori</Text>
                            </Box>
                        </SwiperSlide>


                    </Swiper>

                </Container>

                <Container maxW={"container.xl"} mt={8}>
                    <Box borderLeft={"4px"} borderColor={"specialColors.portland_orange.500"} paddingLeft={2} mb={6}>
                        <Text fontSize='2xl' fontWeight={"semibold"}>En Son Eklenenler</Text>
                    </Box>
                    <SimpleGrid columns={3} spacingX='40px' spacingY='40px'>

                        <Box bg={"white"} boxShadow={"2xl"} minHeight={400} w={"100%"}
                             rounded={"md"} overflow={"hidden"}>

                            <Image src={"/assets/images/1.jpg"} width={"full"} height={220}
                                   objectFit={"cover"}></Image>

                            <VStack align={"start"} my={3} px={4} spacing={4}>
                                <Text fontSize='2xl' fontWeight={"semibold"} lineHeight={"1.6rem"}>Header OneHeader
                                    OneHeader OneHeader OneHeader OneHeader One</Text>

                                <Text textAlign={"justify"}>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                                    Praesent et lectus tortor. Nulla quam ipsum, aliquet commodo tellus ac,
                                    ultricies condimentum leo.</Text>

                                <Button width={"full"}>Teste Git</Button>
                            </VStack>
                        </Box>

                        <Box bg={"white"} boxShadow={"2xl"} minHeight={400} w={"100%"}
                             rounded={"md"} overflow={"hidden"}>

                            <Image src={"/assets/images/3.jpg"} width={"full"} height={220}
                                   objectFit={"cover"}></Image>

                            <VStack align={"start"} my={3} px={4} spacing={4}>
                                <Text fontSize='2xl' fontWeight={"semibold"} lineHeight={"1.6rem"}>Header OneHeader
                                    OneHeader OneHeader OneHeader OneHeader One</Text>

                                <Text textAlign={"justify"}>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                                    Praesent et lectus tortor. Nulla quam ipsum, aliquet commodo tellus ac,
                                    ultricies condimentum leo.</Text>

                                <Button width={"full"}>Teste Git</Button>
                            </VStack>
                        </Box>

                        <Box bg={"white"} boxShadow={"2xl"} minHeight={400} w={"100%"}
                             rounded={"md"} overflow={"hidden"}>

                            <Image src={"/assets/images/2.jpg"} width={"full"} height={220}
                                   objectFit={"cover"}></Image>

                            <VStack align={"start"} my={3} px={4} spacing={4}>
                                <Text fontSize='2xl' fontWeight={"semibold"} lineHeight={"1.6rem"}>Header OneHeader
                                    OneHeader OneHeader OneHeader OneHeader One</Text>

                                <Text textAlign={"justify"}>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                                    Praesent et lectus tortor. Nulla quam ipsum, aliquet commodo tellus ac,
                                    ultricies condimentum leo.</Text>

                                <Button width={"full"}>Teste Git</Button>
                            </VStack>
                        </Box>

                        <Box bg={"white"} boxShadow={"2xl"} minHeight={400} w={"100%"}
                             rounded={"md"} overflow={"hidden"}>

                            <Image src={"/assets/images/2.jpg"} width={"full"} height={220}
                                   objectFit={"cover"}></Image>

                            <VStack align={"start"} my={3} px={4} spacing={4}>
                                <Text fontSize='2xl' fontWeight={"semibold"} lineHeight={"1.6rem"}>Header OneHeader
                                    OneHeader OneHeader OneHeader OneHeader One</Text>

                                <Text textAlign={"justify"}>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                                    Praesent et lectus tortor. Nulla quam ipsum, aliquet commodo tellus ac,
                                    ultricies condimentum leo.</Text>

                                <Button width={"full"}>Teste Git</Button>
                            </VStack>
                        </Box>
                    </SimpleGrid>
                </Container>

            </StandartLayout>

        </>
    )
}