import Head from 'next/head';
import { useRef } from "react";
import { Alert, AlertIcon, VStack } from "@chakra-ui/react";
import { useRouter } from "next/router";
import StandardLayout from "../components/layouts/StandardLayout";
import PickedQuizzesForYou from "../components/quiz_components/PickedQuizzesForYou";
import Categories from "../components/category_components/Categories";
import LastAddedQuizzes from "../components/quiz_components/LastAddedQuizzes";
import { useQuery } from 'react-query';
import { ApiService } from '@/services/api.service';
import ContainerArea from '@/components/ContainerArea';

const Area = () => {
    const categories = useQuery("allCategories", async () => await ApiService.categoryQueries.getAllCategories().then(response => response.data.data));
    const quizzes = useQuery("allQuizzes", async () => await ApiService.quizQueries.getAllQuizzes().then(response => response.data.data));

    if (quizzes.isLoading && categories.isLoading) {
        return (
            <ContainerArea>
                <Alert status='info'>
                    <AlertIcon />
                    Yükleniyor
                </Alert>
            </ContainerArea>
        );
    }

    if (quizzes.isError && categories.isError) {
        return (
            <ContainerArea>
                <Alert status='error'>
                    <AlertIcon />
                    Veriler getirilirken bir sorun oluştu.
                </Alert>
            </ContainerArea>
        );
    }

    return (

            <VStack spacing={4}>
                {/* <PickedQuizzesForYou/> */}
                <Categories data={categories.data} />
                <LastAddedQuizzes data={quizzes.data} />
            </VStack>

    );
};

export default function Home() {

    return (
        <>
            <Head>
                <title>Degree Project</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <StandardLayout>
                <Area />
            </StandardLayout>

        </>
    );
}